apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvs
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3a21482b-accd-4a0d-9bef-dbcc69d437bc"
    keyvaultName: "integrator-vault"
    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret
    tenantId: "186db99d-7751-4212-9f7c-203b1902b039"